### ISSUE TITLE
Add PyPI distribution

### ISSUE THREAD

**Issue by widdowquinn** [HobnobMancer/cazy_webscraper#10]
Instructions are provided for installation *via* `conda`, but many people prefer to use `pip` as their package manage for Python.

Please could `cazy_webscraper` be distributed *via* PyPI? (See, e.g. [PyPI docs](https://pypi.org/help/#publishing))

**Comment by HobnobMancer** [comment]
Added https://pypi.org/project/cazy-webscraper/
