### ISSUE TITLE
No PDB acessions matched and Retrieving no protein structure files

### ISSUE THREAD

**Issue by chagas98** [HobnobMancer/cazy_webscraper#111]
I tried to run basic commands from README and [Documentation](https://cazy-webscraper.readthedocs.io/en/latest/pdb.html). As my primary goal is to retrieve the PDB files, I started creating a local database with 

```
cazy_webscraper <e-mail> --families GH -o GH.db
```
And next, some command to get pdb structures

```
cw_get_pdb_structures GH.db --classes GH pdb
```

However, I got the following output:

```
Using default CAZy class synonyms
Applying CAZy class filter(s)
Retrieving GenBank accessions for selected CAZy classes:   0%| | 0/1 [00:00<?, ?Retrieving CAZymes for CAZy class GH
Retrieving GenBank accessions for selected CAZy classes: 100%|█| 1/1 [00:44<00:0
Retrieving GenBank accessions for selected CAZy families: 0it [00:00, ?it/s]
Applying no taxonomic filters
Loading existing PDB db records: 0it [00:00, ?it/s]
Loading existing Genbank_Pdbs db records: 0it [00:00, ?it/s]
No PDB accessions matched the criteria provided.
Retrieving no protein structure files from PDB

```
I ran different settings with PL, GH, and GT, and I got the same result. 

My system configuration: 

```
Linux 5.19.0-35-generic x86_64
Ubuntu 22.04.2 LTS
conda 23.1.0
```

**Comment by HobnobMancer** [comment]
Hi! Thanks for using `cazy_webscraper`.

After building the local CAZyme database with records downloaded from CAZy, did you retrieve the PDB accessions from UniProt using `cazy_webscraper`?

(_semi-shameless plug of our paper in coming ;)_ ) To summarise a chunk of the [paper](https://www.biorxiv.org/content/10.1101/2022.12.02.518825v1.full) (where it's explained better): When building the local CAZyme database, `cazy_webscraper` parses data from a plain text file dump that's available from CAZy. The text file only contains:
* NCBI protein version accessions
* taxonomic kingdoms
* source organisms
* CAZy family annotations

Therefore, the resulting database only contains that data. - you can check this using `sqlite3` to query the database, and which will return nothing:
```bash
sqlite3 -header GH.db "SELECT * FROM Pdbs"
```

`cw_get_pdb_structures` retrieves the *structure files* from the PDB database for PDB accessions that are **_in_** the local CAZyme database.

So you first need to populate the local CAZyme database with PDB accessions from UniProt, using the [`cw_get_uniprot_data` command](https://cazy-webscraper.readthedocs.io/en/latest/uniprot.html). Hence, the note in the [documentation](https://cazy-webscraper.readthedocs.io/en/latest/pdb.html) stating:

> Note: PDB structure files are retrieved for the **PDB accessions _in_ a local CAZyme database** created using cazy_webscraper.

I'll add an additional note to the documentation to make this clearer - I can see how it doesn't seem obvious
